theme: jekyll-theme-minimal
title: Equal Experts AI Tool Guidance
description: A comprehensive guide to effectively leveraging AI tools and techniques in software development projects.
baseurl: '/ai-tool-guidance'
logo: /assets/images/equal-experts-logo.svg
version: 2.0.4
css_version: 2.0.4

# Build settings
source: .
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules

# Additional settings
markdown: kramdown
show_downloads: false
google_analytics: # Add your Google Analytics tracking ID here if needed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .gitignore
  - CONTRIBUTING.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .DS_Store
