theme: jekyll-theme-minimal
title: Defra AI in the Tool Guidance
description: Guidance on the use of artificial intelligence (AI) tools within the Department for Environment, Food & Rural Affairs (Defra), covering best practices, security considerations, and implementation guidelines.
baseurl: '/defra-ai-tool-guidance'
logo: /assets/images/defra-logo.svg
version: 2.0.3
css_version: 2.0.3

# Build settings
source: .
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules

# Additional settings
markdown: kramdown
show_downloads: false
google_analytics: # Add your Google Analytics tracking ID here if needed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .gitignore
  - CONTRIBUTING.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .DS_Store
  - prompts/